### ISSUE TITLE
crash sometimes with Ctrl+C

### ISSUE THREAD

**Issue by euri10** [ethereum/mix#288]
using Ctrl+C sometimes crashes me, not all the time.
Not very familiar with C++ debugging, hope the backtrace helps a little, if not I can try to provide more info as it happens quite frequently.
I use a compile on Debian from the develop branch and Qt is locally installed.

```
[Thread 0x7fff36ff7700 (LWP 6725) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff3034c10 in QQmlData::isSignalConnected(QAbstractDeclarativeData*, QObject const*, int) ()
   from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Qml.so.5
(gdb) backtrace
#0  0x00007ffff3034c10 in QQmlData::isSignalConnected(QAbstractDeclarativeData*, QObject const*, int) ()
   from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Qml.so.5
#1  0x00007ffff2660857 in QMetaObject::activate(QObject*, int, int, void**) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#2  0x00000000007c7b97 in dev::mix::Clipboard::clipboardChanged (this=0x4448700)
    at /home/lotso/webthree-umbrella/build/mix/moc_Clipboard.cpp:164
#3  0x0000000000717e95 in dev::mix::Clipboard::Clipboard()::{lambda()#1}::operator()() const ()
    at /home/lotso/webthree-umbrella/mix/src/Clipboard.cpp:27
#4  0x0000000000718247 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, dev::mix::Clipboard::Clipboard()::<lambda()> >::call(dev::mix::Clipboard::<lambda()>, void **) (f=..., arg=0x7fffffffd1b0)
    at /home/lotso/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h:494
#5  0x0000000000718219 in QtPrivate::Functor<dev::mix::Clipboard::Clipboard()::<lambda()>, 0>::call<QtPrivate::List<>, void>(dev::mix::Clipboard::<lambda()> &, void *, void **) (f=..., arg=0x7fffffffd1b0) at /home/lotso/Qt/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h:551
#6  0x00000000007181de in QtPrivate::QFunctorSlotObject<dev::mix::Clipboard::Clipboard()::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x33205b0, r=0x16f2ea0, a=0x7fffffffd1b0, ret=0x0)
    at /home/lotso/Qt/5.4/gcc_64/include/QtCore/qobject_impl.h:192
#7  0x00007ffff2660c75 in QMetaObject::activate(QObject*, int, int, void**) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#8  0x00007ffff350771f in QClipboard::emitChanged(QClipboard::Mode) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#9  0x00007fffdc649876 in ?? () from /home/lotso/Qt/5.4/gcc_64/plugins/platforms/libqxcb.so
#10 0x00007ffff35074bf in QClipboard::setMimeData(QMimeData*, QClipboard::Mode) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Gui.so.5
#11 0x00007fffec0b7a07 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#12 0x00007fffed90ad34 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#13 0x00007fffed909d97 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#14 0x00007fffed909fc1 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#15 0x00007fffee63f78a in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#16 0x00007fffee64307b in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#17 0x00007fffee643583 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#18 0x00007fffec0b89b3 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5WebEngineCore.so.5
#19 0x00007ffff2662fd4 in QObject::event(QEvent*) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#20 0x00007ffff76b1294 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#21 0x00007ffff76b4c36 in QApplication::notify(QObject*, QEvent*) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Widgets.so.5
#22 0x000000000070838d in dev::mix::MixApplication::notify (this=0x7fffffffe350, _receiver=0x2481150, _event=0x7fff64236380)
    at /home/lotso/webthree-umbrella/mix/src/MixApplication.cpp:108
#23 0x00007ffff262e8d4 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#24 0x00007ffff26314b8 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#25 0x00007ffff2688c53 in ?? () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#26 0x00007ffff0022fd7 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff0023230 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff00232dc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff2689084 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#30 0x00007ffff262cafb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#31 0x00007ffff2631a15 in QCoreApplication::exec() () from /home/lotso/Qt/5.4/gcc_64/lib/libQt5Core.so.5
#32 0x00000000007919a9 in main (_argc=1, _argv=0x7fffffffe498) at /home/lotso/webthree-umbrella/mix/src/main.cpp:37
(gdb)

```

**Comment by LianaHus** [comment]
https://github.com/ethereum/mix/issues/208
